OJ-1995 code refactoring
govuk-one-login/ipv-cri-otg-hmrc pull request #16
Opened 2023-10-27 16:02 UTC by rahulGDS

## Proposed changes

### What changed

change the folder structure and code refactoring

### Why did it change

### Issue tracking

- [OJ-1995](https://govukverify.atlassian.net/browse/OJ-1995)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-10-27 16:15 UTC, surajkumar requested changes

2023-10-27 16:15 UTC, surajkumar commented on integration-tests/setEnvVars.js
> +  "arn:aws:states:eu-west-2:404250751813:stateMachine:pdv-matching-NinoCheck";
Change this to reflect OTG

2023-10-27 16:15 UTC, surajkumar commented on integration-tests/setEnvVars.js
> +process.env.NINO_ATTEMPTS_TABLE = "pdv-matching-nino-attempts";
Remove these nino specific env vars

2023-10-27 16:15 UTC, surajkumar commented on integration-tests/tests/.DS_Store
Delete this file

2023-10-27 16:15 UTC, surajkumar commented on integration-tests/tests/aws/.DS_Store
Delete this file

2023-10-27 16:15 UTC, surajkumar commented on integration-tests/tests/aws/generate-totp/.DS_Store
Delete this file

2023-10-27 16:15 UTC, surajkumar commented on integration-tests/tests/mocked/.DS_Store
Delete this file

2023-10-27 16:15 UTC, surajkumar commented on integration-tests/tests/mocked/generate-totp/.DS_Store
Delete this file

2023-10-27 16:15 UTC, surajkumar commented on integration-tests/tests/mocked/generate-totp/docker-compose.yaml
> +    container_name: "otg-generate"
can you make this name consistent with the others

2023-10-30 14:03 UTC, surajkumar approved these changes

2023-10-30 15:09 UTC, jkunle approved these changes

2023-10-30 15:10 UTC, jkunle commented
Please try and re-organise the commits, so it is a lot easier to review. I think this could be 3 different PR's or 3 commits:
• Code refactoring
• Boilerplate added for integration tests
• Added Github Actions

2023-10-30 15:16 UTC, merged